# Generated by Django 4.0.6 on 2022-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='qr_image',
            field=models.ImageField(blank=True, default='media/dummy qr.png', null=True, upload_to='qrcodes'),
        ),
    ]
