# Generated by Django 4.0.6 on 2022-08-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="text",
            options={
                "ordering": ("-created_on",),
                "verbose_name": "Text",
                "verbose_name_plural": "Texts",
            },
        ),
        migrations.RemoveField(
            model_name="text",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="text",
            name="qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes"),
        ),
    ]
