# Generated by Django 4.0.6 on 2022-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_text_options_remove_text_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='qr_image',
            field=models.ImageField(blank=True, default='media/dummy qr.png', null=True, upload_to='qrcodes'),
        ),
    ]
