# Generated by Django 4.0.6 on 2022-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
