# Generated by Django 4.0.6 on 2022-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
