# Generated by Django 4.0.6 on 2022-08-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
    ]
