# Generated by Django 4.0.6 on 2022-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
