# Generated by Django 4.0.6 on 2022-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_created_by_alter_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='qr_image',
            field=models.ImageField(blank=True, default='media/dummy qr.png', null=True, upload_to='qrcodes'),
        ),
    ]
