# Generated by Django 4.0.6 on 2022-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_alter_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(default='https://'),
        ),
    ]
