# Generated by Django 4.0.6 on 2022-08-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_alter_website_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
